BEGIN TRANSACTION;

DROP TABLE IF EXISTS "USERS";
CREATE TABLE "USERS" (
"CODE" INTEGER PRIMARY KEY  NOT NULL , 
"NAME" VARCHAR NOT NULL , 
"SURNAME" VARCHAR NOT NULL , 
"USERNAME" VARCHAR NOT NULL  UNIQUE , 
"PASSWORD" VARCHAR NOT NULL 
);


DROP TABLE IF EXISTS "ROLES";
CREATE TABLE "ROLES" (
"CODE" INTEGER PRIMARY KEY  NOT NULL , 
"NAME" VARCHAR NOT NULL UNIQUE
);

DROP TABLE IF EXISTS "PAGES";
CREATE TABLE "PAGES" (
"CODE" INTEGER PRIMARY KEY  NOT NULL , 
"DESCRIPTION" VARCHAR NOT NULL UNIQUE
);

DROP TABLE IF EXISTS "USER_ROLES";
CREATE TABLE "USER_ROLES" (
"CODE" INTEGER PRIMARY KEY  NOT NULL ,
"USER_CODE" INTEGER NOT NULL , 
"ROLE_CODE" INTEGER NOT NULL ,
FOREIGN KEY (USER_CODE) REFERENCES USERS(CODE),
FOREIGN KEY (ROLE_CODE) REFERENCES ROLES(CODE)
);

DROP TABLE IF EXISTS "ROLE_PAGES";
CREATE TABLE "ROLE_PAGES" (
"CODE" INTEGER PRIMARY KEY  NOT NULL ,
"ROLE_CODE" INTEGER NOT NULL , 
"PAGE_CODE" INTEGER NOT NULL ,
FOREIGN KEY (ROLE_CODE) REFERENCES ROLES(CODE),
FOREIGN KEY (PAGE_CODE) REFERENCES PAGES(CODE)
);

COMMIT;
